import type { MarketConfig } from "./types";

export const maMarket: MarketConfig = {
  marketId: "ma",
  locales: ["fr-MA", "ar-MA", "en-MA"],
  defaultLocale: "fr-MA",
  currency: "MAD",
  currencySymbol: "MAD",
  paymentProviders: ["cmi", "stripe"],
  depositAmount: 1000,
  legal: {
    termsUrl: "/fr-MA/conditions-de-vente",
    privacyUrl: "/fr-MA/protection-des-donnees",
    cookieRegime: "gdpr-like",
    dataResidency: "EU",
  },
  whatsappBusinessId: process.env.WHATSAPP_BUSINESS_ID,
  dealerNetwork: [
    {
      id: "casa-atlas-motors",
      name: "Atlas Motors Casablanca",
      city: "Casablanca",
      region: "Casablanca-Settat",
      address: "Boulevard Moulay Youssef, Casablanca",
      phone: "+212 522 00 00 00",
      whatsapp: "+212 600 00 00 00",
      lat: 33.5731,
      lng: -7.5898,
    },
    {
      id: "rabat-auto-hall",
      name: "Auto Hall Rabat",
      city: "Rabat",
      region: "Rabat-Salé-Kénitra",
      address: "Avenue Mohammed V, Rabat",
      phone: "+212 537 00 00 00",
      whatsapp: "+212 600 00 00 01",
      lat: 34.0209,
      lng: -6.8416,
    },
    {
      id: "marrakech-auto",
      name: "Auto Hall Marrakech",
      city: "Marrakech",
      region: "Marrakech-Safi",
      address: "Route de Casablanca, Marrakech",
      phone: "+212 524 00 00 00",
      whatsapp: "+212 600 00 00 02",
      lat: 31.6295,
      lng: -7.9811,
    },
  ],
  financingPartners: [
    { id: "attijariwafa", name: "Attijariwafa Bank" },
    { id: "boa", name: "Bank of Africa" },
    { id: "cih", name: "CIH Bank" },
  ],
  features: {
    atlasVoice: true,
    generativeImagery: true,
    personalizedVideo: true,
    financingAdvisor: true,
    bespokePDF: true,
    cmiDeposit: true,
  },
};
